apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: tomcat:10.1.18
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: syndic-war
              mountPath: /usr/local/tomcat/webapps/Syndic.war
      volumes:
        - name: syndic-war
          hostPath:
            path: ./target/Syndic.war
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
